delete from users;
insert into users values (null, 'zorichev', 'viktor.zorichev@gmail.com', '123');
insert into users values (null, 'beaver', 'beaver@gmail.com', '123');
insert into users values (null, 'martlet', 'martlet@gmail.com', '123456');
delete from authors;
insert into authors values (null, 'George R. R. Martin');
insert into authors values (null, 'Stephen King');
insert into authors values (null, 'Stanislaw Lem');
insert into authors values (null, 'Harry Harrison');
insert into authors values (null, 'Tom Shippey');
insert into authors values (null, 'Mark Pilgrim');
delete from books;
insert into books values (null, 'A Dance with Dragons');
insert into books values (null, 'The Gunslinger');
insert into books values (null, 'Solaris');
insert into books values (null, 'The Hammer and the Cross');
insert into books values (null, 'Dive Into Python 3');
insert into books values (null, 'The Technicolor Time Machine');
delete from books_authors;
insert into books_authors values (1, 1);
insert into books_authors values (2, 2);
insert into books_authors values (3, 3);
insert into books_authors values (4, 4);
insert into books_authors values (4, 5);
insert into books_authors values (5, 6);
insert into books_authors values (6, 4);